name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Gradle Mirror (Aliyun)  # 强制使用国内镜像加速
        run: |
          sed -i "s|google()|maven { url 'https://maven.aliyun.com/repository/google' }|g" build.gradle
          sed -i "s|jcenter()|maven { url 'https://maven.aliyun.com/repository/public' }|g" build.gradle
          sed -i "s|mavenCentral()|maven { url 'https://maven.aliyun.com/repository/public' }|g" build.gradle

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --scan  # 启用 Gradle Scan 分析
